/* Catalogue des cartes du set Blurness 3.
   Fichier de donnees statique : pas de backend, tout est charge par le
   navigateur au chargement de la page. */

const CARTES = [
  {
    id: "essence-rose",
    nom: "Essence Rose",
    numero: "001",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 3.17,
    stock: 30,
    image: "assets/cards/001-essence-rose.webp",
  },
  {
    id: "essence-orange",
    nom: "Essence Orange",
    numero: "002",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Commune",
    prix: 2.83,
    stock: 39,
    image: "assets/cards/002-essence-orange.webp",
  },
  {
    id: "essence-jade",
    nom: "Essence Jade",
    numero: "003",
    essence: "Jade",
    couleur: "#2fae86",
    rarete: "Commune",
    prix: 3.81,
    stock: 21,
    image: "assets/cards/003-essence-jade.webp",
  },
  {
    id: "essence-violette",
    nom: "Essence Violette",
    numero: "004",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Commune",
    prix: 3.82,
    stock: 25,
    image: "assets/cards/004-essence-violette.webp",
  },
  {
    id: "essence-jaune",
    nom: "Essence Jaune",
    numero: "005",
    essence: "Jaune",
    couleur: "#e0c341",
    rarete: "Legendaire",
    prix: 38.89,
    stock: 0,
    image: "assets/cards/005-essence-jaune.webp",
  },
  {
    id: "essence-mauve",
    nom: "Essence Mauve",
    numero: "006",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 3.25,
    stock: 30,
    image: "assets/cards/006-essence-mauve.webp",
  },
  {
    id: "essence-verte",
    nom: "Essence Verte",
    numero: "007",
    essence: "Verte",
    couleur: "#5aba48",
    rarete: "Commune",
    prix: 4.21,
    stock: 21,
    image: "assets/cards/007-essence-verte.webp",
  },
  {
    id: "essence-bleue",
    nom: "Essence Bleue",
    numero: "008",
    essence: "Bleue",
    couleur: "#3f7fe0",
    rarete: "Commune",
    prix: 3.36,
    stock: 10,
    image: "assets/cards/008-essence-bleue.webp",
  },
  {
    id: "essence-azur",
    nom: "Essence Azur",
    numero: "009",
    essence: "Azur",
    couleur: "#3fb8e0",
    rarete: "Commune",
    prix: 4.68,
    stock: 11,
    image: "assets/cards/009-essence-azur.webp",
  },
  {
    id: "vandale",
    nom: "Vandale",
    numero: "011",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 4.20,
    stock: 0,
    image: "assets/cards/011-vandale.webp",
  },
  {
    id: "squeezie-le-toxique",
    nom: "Squeezie Le Toxique",
    numero: "012",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Legendaire",
    prix: 45.65,
    stock: 6,
    image: "assets/cards/012-squeezie-le-toxique.webp",
  },
  {
    id: "pas-compris",
    nom: "Pas compris",
    numero: "013",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 3.13,
    stock: 25,
    image: "assets/cards/013-pas-compris.webp",
  },
  {
    id: "tout-commence-ici",
    nom: "Tout Commence Ici",
    numero: "017",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 4.56,
    stock: 21,
    image: "assets/cards/017-tout-commence-ici.webp",
  },
  {
    id: "buy-bundle-m8",
    nom: "BUY BUNDLE M8 !!",
    numero: "018",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 4.88,
    stock: 2,
    image: "assets/cards/018-buy-bundle-m8.webp",
  },
  {
    id: "oce-pce",
    nom: "OCE/PCE",
    numero: "019",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 3.20,
    stock: 33,
    image: "assets/cards/019-oce-pce.webp",
  },
  {
    id: "namifique",
    nom: "Namifique",
    numero: "022",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Rare",
    prix: 12.36,
    stock: 30,
    image: "assets/cards/022-namifique.webp",
  },
  {
    id: "marteen-supreme",
    nom: "Marteen Supreme",
    numero: "023",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 4.63,
    stock: 27,
    image: "assets/cards/023-marteen-supreme.webp",
  },
  {
    id: "gentle-mates-minny",
    nom: "Gentle Mates Minny",
    numero: "025",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 4.28,
    stock: 2,
    image: "assets/cards/025-gentle-mates-minny.webp",
  },
  {
    id: "pause-technique",
    nom: "Pause Technique",
    numero: "026",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Rare",
    prix: 9.79,
    stock: 16,
    image: "assets/cards/026-pause-technique.webp",
  },
  {
    id: "remontada",
    nom: "Remontada",
    numero: "027",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 2.97,
    stock: 40,
    image: "assets/cards/027-remontada.webp",
  },
  {
    id: "championnes-d-europe",
    nom: "CHAMPIONNES D'EUROPE",
    numero: "028",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Rare",
    prix: 9.70,
    stock: 24,
    image: "assets/cards/028-championnes-d-europe.webp",
  },
  {
    id: "pollo",
    nom: "Pollo",
    numero: "029",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Rare",
    prix: 14.80,
    stock: 32,
    image: "assets/cards/029-pollo.webp",
  },
  {
    id: "worlds-lyon",
    nom: "Worlds Lyon",
    numero: "030",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Legendaire",
    prix: 42.96,
    stock: 27,
    image: "assets/cards/030-worlds-lyon.webp",
  },
  {
    id: "moi-je-suis-coach",
    nom: "Moi je suis coach",
    numero: "031",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Commune",
    prix: 3.78,
    stock: 33,
    image: "assets/cards/031-moi-je-suis-coach.webp",
  },
  {
    id: "invitation",
    nom: "Invitation",
    numero: "032",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Commune",
    prix: 2.53,
    stock: 3,
    image: "assets/cards/032-invitation.webp",
  },
  {
    id: "visa-refuse",
    nom: "Visa Refusé",
    numero: "033",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Commune",
    prix: 4.49,
    stock: 6,
    image: "assets/cards/033-visa-refuse.webp",
  },
  {
    id: "vanyabubu",
    nom: "Vanyabubu",
    numero: "034",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Rare",
    prix: 8.14,
    stock: 5,
    image: "assets/cards/034-vanyabubu.webp",
  },
  {
    id: "pitchounes",
    nom: "Pitchounes",
    numero: "035",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Rare",
    prix: 14.30,
    stock: 19,
    image: "assets/cards/035-pitchounes.webp",
  },
  {
    id: "l-oeil-de-nikof",
    nom: "L'oeil de Nikof",
    numero: "037",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Rare",
    prix: 9.22,
    stock: 0,
    image: "assets/cards/037-l-oeil-de-nikof.webp",
  },
  {
    id: "zero-soucis",
    nom: "Zéro Soucis",
    numero: "039",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Rare",
    prix: 13.32,
    stock: 27,
    image: "assets/cards/039-zero-soucis.webp",
  },
  {
    id: "reverse-squeeze",
    nom: "Reverse Squeeze",
    numero: "042",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Commune",
    prix: 4.15,
    stock: 18,
    image: "assets/cards/042-reverse-squeeze.webp",
  },
  {
    id: "blblblbl",
    nom: "BLBLBLBL",
    numero: "043",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Commune",
    prix: 3.90,
    stock: 31,
    image: "assets/cards/043-blblblbl.webp",
  },
  {
    id: "zzzzzzz",
    nom: "Zzzzzzz",
    numero: "045",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Rare",
    prix: 9.11,
    stock: 17,
    image: "assets/cards/045-zzzzzzz.webp",
  },
  {
    id: "champions-du-major",
    nom: "CHAMPIONS DU MAJOR",
    numero: "047",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Commune",
    prix: 4.40,
    stock: 35,
    image: "assets/cards/047-champions-du-major.webp",
  },
  {
    id: "champions-du-major-2",
    nom: "CHAMPIONS DU MAJOR",
    numero: "048",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Commune",
    prix: 3.54,
    stock: 10,
    image: "assets/cards/048-champions-du-major.webp",
  },
  {
    id: "le-roi-des-rois",
    nom: "Le Roi des rois",
    numero: "049",
    essence: "Jaune",
    couleur: "#e0c341",
    rarete: "Commune",
    prix: 3.61,
    stock: 23,
    image: "assets/cards/049-le-roi-des-rois.webp",
  },
  {
    id: "la-planete",
    nom: "La Planète",
    numero: "051",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 2.63,
    stock: 38,
    image: "assets/cards/051-la-planete.webp",
  },
  {
    id: "target-missed",
    nom: "Target Missed",
    numero: "055",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 3.92,
    stock: 14,
    image: "assets/cards/055-target-missed.webp",
  },
  {
    id: "maillot-maudit",
    nom: "Maillot Maudit",
    numero: "056",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 4.58,
    stock: 19,
    image: "assets/cards/056-maillot-maudit.webp",
  },
  {
    id: "siborg",
    nom: "Siborg",
    numero: "057",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Rare",
    prix: 11.98,
    stock: 32,
    image: "assets/cards/057-siborg.webp",
  },
  {
    id: "ghosty-in-finals",
    nom: "Ghosty in Finals",
    numero: "058",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 4.82,
    stock: 38,
    image: "assets/cards/058-ghosty-in-finals.webp",
  },
  {
    id: "baby-driver",
    nom: "Baby Driver",
    numero: "059",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Legendaire",
    prix: 57.21,
    stock: 40,
    image: "assets/cards/059-baby-driver.webp",
  },
  {
    id: "gotaga-pose",
    nom: "Gotaga Pose",
    numero: "060",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 3.72,
    stock: 6,
    image: "assets/cards/060-gotaga-pose.webp",
  },
  {
    id: "champions-du-major-3",
    nom: "CHAMPIONS DU MAJOR",
    numero: "061",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 3.22,
    stock: 2,
    image: "assets/cards/061-champions-du-major.webp",
  },
  {
    id: "just-passion",
    nom: "Just Passion",
    numero: "063",
    essence: "Verte",
    couleur: "#5aba48",
    rarete: "Commune",
    prix: 4.09,
    stock: 31,
    image: "assets/cards/063-just-passion.webp",
  },
  {
    id: "calma",
    nom: "Calma",
    numero: "064",
    essence: "Verte",
    couleur: "#5aba48",
    rarete: "Commune",
    prix: 4.30,
    stock: 10,
    image: "assets/cards/064-calma.webp",
  },
  {
    id: "bwarks",
    nom: "Bwarks",
    numero: "065",
    essence: "Bleue",
    couleur: "#3f7fe0",
    rarete: "Rare",
    prix: 12.28,
    stock: 13,
    image: "assets/cards/065-bwarks.webp",
  },
  {
    id: "jus-de-bagarre",
    nom: "Jus de bagarre",
    numero: "066",
    essence: "Bleue",
    couleur: "#3f7fe0",
    rarete: "Commune",
    prix: 4.64,
    stock: 27,
    image: "assets/cards/066-jus-de-bagarre.webp",
  },
  {
    id: "1-chance",
    nom: "1% chance",
    numero: "068",
    essence: "Bleue",
    couleur: "#3f7fe0",
    rarete: "Commune",
    prix: 4.03,
    stock: 10,
    image: "assets/cards/068-1-chance.webp",
  },
  {
    id: "99-faith",
    nom: "99% faith",
    numero: "069",
    essence: "Bleue",
    couleur: "#3f7fe0",
    rarete: "Legendaire",
    prix: 48.72,
    stock: 33,
    image: "assets/cards/069-99-faith.webp",
  },
  {
    id: "l-arme-nucleaire",
    nom: "L'Arme Nucléaire",
    numero: "070",
    essence: "Azur",
    couleur: "#3fb8e0",
    rarete: "Commune",
    prix: 4.02,
    stock: 0,
    image: "assets/cards/070-l-arme-nucleaire.webp",
  },
  {
    id: "versus-fighting",
    nom: "Versus Fighting",
    numero: "072",
    essence: "Azur",
    couleur: "#3fb8e0",
    rarete: "Commune",
    prix: 4.35,
    stock: 35,
    image: "assets/cards/072-versus-fighting.webp",
  },
  {
    id: "leakof",
    nom: "Leakof",
    numero: "073",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 29.02,
    stock: 4,
    image: "assets/cards/073-leakof.webp",
  },
  {
    id: "l-heritier",
    nom: "L'Héritier",
    numero: "073",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 2.72,
    stock: 8,
    image: "assets/cards/073-l-heritier.webp",
  },
  {
    id: "grand-respect",
    nom: "Grand Respect",
    numero: "075",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 12.15,
    stock: 13,
    image: "assets/cards/075-grand-respect.webp",
  },
  {
    id: "petrodollars",
    nom: "Pétrodollars",
    numero: "076",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.52,
    stock: 32,
    image: "assets/cards/076-petrodollars.webp",
  },
  {
    id: "brawks-deter",
    nom: "Brawks Déter",
    numero: "078",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 10.56,
    stock: 17,
    image: "assets/cards/078-brawks-deter.webp",
  },
  {
    id: "le-chevalier-rose",
    nom: "Le Chevalier Rose",
    numero: "079",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.11,
    stock: 40,
    image: "assets/cards/079-le-chevalier-rose.webp",
  },
  {
    id: "instalock",
    nom: "Instalock",
    numero: "080",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.85,
    stock: 7,
    image: "assets/cards/080-instalock.webp",
  },
  {
    id: "mon-cogneur",
    nom: "Mon Cogneur",
    numero: "082",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 3.42,
    stock: 29,
    image: "assets/cards/082-mon-cogneur.webp",
  },
  {
    id: "barakataga",
    nom: "Barakataga",
    numero: "083",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 2.74,
    stock: 11,
    image: "assets/cards/083-barakataga.webp",
  },
  {
    id: "mercato",
    nom: "Mercato",
    numero: "084",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.83,
    stock: 33,
    image: "assets/cards/084-mercato.webp",
  },
  {
    id: "la-chevaliere",
    nom: "La Chevalière",
    numero: "085",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 2.79,
    stock: 10,
    image: "assets/cards/085-la-chevaliere.webp",
  },
  {
    id: "cooked",
    nom: "Cooked",
    numero: "086",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 2.84,
    stock: 34,
    image: "assets/cards/086-cooked.webp",
  },
  {
    id: "gros-bonnet",
    nom: "Gros Bonnet",
    numero: "088",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 37.35,
    stock: 40,
    image: "assets/cards/088-gros-bonnet.webp",
  },
  {
    id: "m4",
    nom: "M4",
    numero: "089",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 3.07,
    stock: 0,
    image: "assets/cards/089-m4.webp",
  },
  {
    id: "la-luxueuse-i",
    nom: "La Luxueuse I",
    numero: "090",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 9.08,
    stock: 5,
    image: "assets/cards/090-la-luxueuse-i.webp",
  },
  {
    id: "la-luxueuse-ii",
    nom: "La Luxueuse II",
    numero: "091",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 12.60,
    stock: 31,
    image: "assets/cards/091-la-luxueuse-ii.webp",
  },
  {
    id: "clim",
    nom: "Clim",
    numero: "093",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 41.25,
    stock: 0,
    image: "assets/cards/093-clim.webp",
  },
  {
    id: "alerte-leak",
    nom: "Alerte Leak",
    numero: "094",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 10.61,
    stock: 30,
    image: "assets/cards/094-alerte-leak.webp",
  },
  {
    id: "one-more",
    nom: "ONE MORE",
    numero: "095",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.60,
    stock: 23,
    image: "assets/cards/095-one-more.webp",
  },
  {
    id: "tunnel",
    nom: "Tunnel",
    numero: "096",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.44,
    stock: 28,
    image: "assets/cards/096-tunnel.webp",
  },
  {
    id: "tweet-la-defaite",
    nom: "Tweet la Défaite",
    numero: "097",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.46,
    stock: 38,
    image: "assets/cards/097-tweet-la-defaite.webp",
  },
  {
    id: "doig-dance",
    nom: "Doig'Dance",
    numero: "098",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 53.30,
    stock: 2,
    image: "assets/cards/098-doig-dance.webp",
  },
  {
    id: "meta-coeurs",
    nom: "Méta Coeurs",
    numero: "099",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.47,
    stock: 23,
    image: "assets/cards/099-meta-coeurs.webp",
  },
  {
    id: "meta-f-ck",
    nom: "Méta F*ck",
    numero: "100",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 11.75,
    stock: 14,
    image: "assets/cards/100-meta-f-ck.webp",
  },
  {
    id: "le-loup-du-game",
    nom: "Le Loup du Game",
    numero: "101",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.28,
    stock: 25,
    image: "assets/cards/101-le-loup-du-game.webp",
  },
  {
    id: "slay",
    nom: "SLAY",
    numero: "102",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 14.33,
    stock: 10,
    image: "assets/cards/102-slay.webp",
  },
  {
    id: "monster",
    nom: "Monster",
    numero: "103",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.61,
    stock: 4,
    image: "assets/cards/103-monster.webp",
  },
  {
    id: "joueur-de-l-ombre",
    nom: "Joueur de l'ombre",
    numero: "103",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.20,
    stock: 13,
    image: "assets/cards/103-joueur-de-l-ombre.webp",
  },
  {
    id: "lofi-girl",
    nom: "Lofi Girl",
    numero: "105",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 3.19,
    stock: 4,
    image: "assets/cards/105-lofi-girl.webp",
  },
  {
    id: "m16",
    nom: "M16",
    numero: "106",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.44,
    stock: 0,
    image: "assets/cards/106-m16.webp",
  },
  {
    id: "trahison",
    nom: "Trahison++",
    numero: "107",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 10.23,
    stock: 39,
    image: "assets/cards/107-trahison.webp",
  },
  {
    id: "keynote",
    nom: "Keynote",
    numero: "109",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 25.53,
    stock: 11,
    image: "assets/cards/109-keynote.webp",
  },
  {
    id: "hatewatch",
    nom: "Hatewatch",
    numero: "110",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 14.57,
    stock: 26,
    image: "assets/cards/110-hatewatch.webp",
  },
  {
    id: "leakof-2",
    nom: "Leakof",
    numero: "111",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.41,
    stock: 27,
    image: "assets/cards/111-leakof.webp",
  },
  {
    id: "la-gaming-house",
    nom: "La Gaming House",
    numero: "112",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.14,
    stock: 4,
    image: "assets/cards/112-la-gaming-house.webp",
  },
  {
    id: "m8-resilience",
    nom: "M8 Résilience",
    numero: "112",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 3.71,
    stock: 21,
    image: "assets/cards/112-m8-resilience.webp",
  },
  {
    id: "sbg",
    nom: "SBG",
    numero: "114",
    essence: "Rose",
    couleur: "#e56aa8",
    rarete: "Commune",
    prix: 3.25,
    stock: 0,
    image: "assets/cards/114-sbg.webp",
  },
  {
    id: "champions-du-monde",
    nom: "CHAMPIONS DU MONDE !",
    numero: "115",
    essence: "Orange",
    couleur: "#e8853a",
    rarete: "Legendaire",
    prix: 27.25,
    stock: 7,
    image: "assets/cards/115-champions-du-monde.webp",
  },
  {
    id: "la-releve",
    nom: "La Relève",
    numero: "117",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 4.62,
    stock: 0,
    image: "assets/cards/117-la-releve.webp",
  },
  {
    id: "gotaga-dance",
    nom: "Gotaga Dance",
    numero: "118",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Rare",
    prix: 9.69,
    stock: 21,
    image: "assets/cards/118-gotaga-dance.webp",
  },
  {
    id: "gotaga-circus",
    nom: "Gotaga Circus",
    numero: "119",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Commune",
    prix: 4.22,
    stock: 0,
    image: "assets/cards/119-gotaga-circus.webp",
  },
  {
    id: "le-marionnettiste",
    nom: "Le Marionnettiste",
    numero: "121",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Rare",
    prix: 8.95,
    stock: 2,
    image: "assets/cards/121-le-marionnettiste.webp",
  },
  {
    id: "la-luxueuse-iii",
    nom: "La Luxueuse III",
    numero: "123",
    essence: "Neutre",
    couleur: "#9aa3b5",
    rarete: "Legendaire",
    prix: 26.22,
    stock: 8,
    image: "assets/cards/123-la-luxueuse-iii.webp",
  },
  {
    id: "brawks-trop-deter",
    nom: "Brawks Trop Déter",
    numero: "125",
    essence: "Violette",
    couleur: "#8a6ae5",
    rarete: "Rare",
    prix: 14.81,
    stock: 20,
    image: "assets/cards/125-brawks-trop-deter.webp",
  },
  {
    id: "paris-gentle-mates",
    nom: "Paris Gentle Mates",
    numero: "127",
    essence: "Mauve",
    couleur: "#b46ae5",
    rarete: "Commune",
    prix: 4.17,
    stock: 30,
    image: "assets/cards/127-paris-gentle-mates.webp",
  },
];

const ESSENCES = [
  { nom: "Rose", couleur: "#e56aa8", logo: "assets/teams/team-01.svg" },
  { nom: "Orange", couleur: "#e8853a", logo: "assets/teams/team-02.svg" },
  { nom: "Jade", couleur: "#2fae86", logo: "assets/teams/team-03.svg" },
  { nom: "Violette", couleur: "#8a6ae5", logo: "assets/teams/team-04.svg" },
  { nom: "Jaune", couleur: "#e0c341", logo: "assets/teams/team-05.svg" },
  { nom: "Mauve", couleur: "#b46ae5", logo: "assets/teams/team-06.svg" },
  { nom: "Verte", couleur: "#5aba48", logo: "assets/teams/team-07.svg" },
  { nom: "Bleue", couleur: "#3f7fe0", logo: "assets/teams/team-08.svg" },
  { nom: "Azur", couleur: "#3fb8e0", logo: "assets/teams/team-09.svg" },
  { nom: "Neutre", couleur: "#9aa3b5", logo: "assets/teams/team-10.svg" },
];

const RARETES = ["Commune", "Rare", "Legendaire"];
